services:
  - type: web
    name: ravuricoltd-channelmanager-ui
    env: python
    plan: free

    # Build should ONLY install deps. Do NOT import CSV here (it resets DB on every deploy).
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p backend/static/app

    # SQLite works best with ONE gunicorn process; threads are fine.
    startCommand: gunicorn -w 1 -k gthread --threads 8 --timeout 120 --keep-alive 5 --chdir backend -b 0.0.0.0:$PORT server:app

    # Health check so Render won't time out.
    healthCheckPath: /health

    envVars:
      # --- REQUIRED (set REAL values in Render dashboard; keep placeholders in git) ---
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ADMIN_EMAIL
        value: ${ADMIN_EMAIL}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
      - key: APP_LANG_DEFAULT
        value: en
      - key: TZ
        value: Asia/Bangkok

      # Keep a single process for SQLite stability
      - key: WEB_CONCURRENCY
        value: "1"

      # --- STRIPE (set your keys in Render env) ---
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: STRIPE_PUBLISHABLE_KEY
        value: ${STRIPE_PUBLISHABLE_KEY}

      # --- EMAIL ALERT SETTINGS (optional; set in Render env) ---
      - key: SMTP_SERVER
        value: ${SMTP_SERVER}
      - key: SMTP_PORT
        value: ${SMTP_PORT}
      - key: SMTP_USER
        value: ${SMTP_USER}
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
      - key: ALERT_TO
        value: ${ALERT_TO}

      # --- DATABASE on persistent disk ---
      - key: DATABASE_URL
        value: sqlite:////var/data/channel_manager.db

    # Persistent disk so your SQLite DB survives restarts/redeploys.
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
