services:
  - type: web
    name: ravuricoltd-channelmanager-ui
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python backend/import_properties.py backend/ota_properties_prefilled.csv
      npm ci --prefix frontend
      npm run build --prefix frontend
      mkdir -p backend/static/app && cp -r frontend/dist/* backend/static/app/
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT backend.server:app
    envVars:
      - key: ADMIN_EMAIL
        value: pradeep@ravuricoltd.com
      - key: ADMIN_PASSWORD
        value: ChangeMe123!
      - key: STRIPE_SECRET_KEY
        value: sk_test_4eC39HqLyjWDarjtT1zdp7dc
      - key: TZ
        value: Asia/Bangkok
