services:
  - type: web
    name: ravuricoltd-channelmanager-ui
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python backend/import_properties.py backend/ota_properties_prefilled.csv
      mkdir -p backend/static/app

    startCommand: gunicorn -w 2 -k gthread --threads 8 --timeout 120 --keep-alive 5 --chdir backend -b 0.0.0.0:$PORT server:app

    healthCheckPath: /health

    envVars:
      # --- REQUIRED ---
      - key: SECRET_KEY
        value: mysecretkey12345
      - key: ADMIN_EMAIL
        value: pradeep@ravuricoltd.com
      - key: ADMIN_PASSWORD
        value: Radhika1
      - key: APP_LANG_DEFAULT
        value: en
      - key: TZ
        value: Asia/Bangkok
      - key: WEB_CONCURRENCY
        value: "2"

      # --- STRIPE LIVE KEYS (replace with your real ones from Stripe) ---
      - key: STRIPE_SECRET_KEY
        value: sk_live_xxxxxxxxxxxxxxxxxxxxxxxxx
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_live_xxxxxxxxxxxxxxxxxxxxxxxxx

      # --- EMAIL ALERT SETTINGS ---
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: rppchowdary@gmail.com
      - key: SMTP_PASSWORD
        value: atcnjjugbspoxzhc
      - key: ALERT_TO
        value: pradeep@ravuricoltd.com

      # --- DATABASE ---
      - key: DATABASE_URL
        value: sqlite:////var/data/channel_manager.db

    # --- PERSISTENT STORAGE ---
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
